### ISSUE TITLE
我新建了一个项目，lib下按你的代码拷贝进去，能够正常运行，但是视频播放不了，你的原项目就可以，是iOS目录有修改什么吗？

### ISSUE THREAD

**Issue by hihey** [Mayandev/morec#11]
我新建了一个项目，lib下按你的代码拷贝进去，能够正常运行，但是视频播放不了，你的原项目就可以，是iOS目录有修改什么吗？或者其他需要注意的地方吗

**Comment by Mayandev** [comment]
iOS 目录添加了一些存储和访问网络的权限。

忘了说了，视频播放插件无法在 iOS 模拟器上运行。具体请看[issues](https://github.com/flutter/flutter/issues/14647)，不过 bug 好像修复了。
