### ISSUE TITLE
run不了

### ISSUE THREAD

**Issue by shipinbaoku** [Mayandev/morec#12]
D:\morecNew>flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              1.7s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "D:\morecNew\android\gradlew.bat" exited abnormally:

> Configure project :app

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate{} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\morecNew\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not resolve com.android.tools.build:gradle:3.2.1.
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource
         'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not HEAD
            'https://maven.aliyun.com/repository/google/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > Connect to 127.0.0.1:6600 [/127.0.0.1] failed: Connection refused: connect
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource
         'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not HEAD
            'https://maven.aliyun.com/repository/jcenter/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > Connect to 127.0.0.1:6600 [/127.0.0.1] failed: Connection refused: connect
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource
         'http://maven.aliyun.com/nexus/content/groups/public/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not HEAD
            'http://maven.aliyun.com/nexus/content/groups/public/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.               > Connect to 127.0.0.1:6600 [/127.0.0.1] failed: Connection refused: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
  Command: D:\morecNew\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder.

**Comment by Mayandev** [comment]
请重新 pull 项目
