### ISSUE TITLE
fork别人代码没说明？

### ISSUE THREAD

**Issue by Lotus-Blue** [Mayandev/morec#13]
原代码处https://github.com/dengchaojie/flutterDemo

**Comment by Lotus-Blue** [comment]
我还看到一个去年的项目代码，也是跟这个一样（豆瓣电影+代码相同），但忘记是哪个了，你这个只是改了myscene界面而已，其他代码几乎一样。总之fork别人代码最好说下吧，尊重别人劳动成果

**Comment by Mayandev** [comment]
回复你第一条：谁fork谁呢，麻烦看清楚项目的创建时间。
回复你第二条：麻烦贴出代码相同的项目地址

ps：我所有的代码都是我一行一行敲的，如果你硬要说我是fork别人的，麻烦拿出确凿的证据

**Comment by Mayandev** [comment]
> 我还看到一个去年的项目代码，也是跟这个一样（豆瓣电影+代码相同），但忘记是哪个了，你这个只是改了myscene界面而已，其他代码几乎一样。总之fork别人代码最好说下吧，尊重别人劳动成果

回复你第一条：谁fork谁呢，麻烦看清楚项目的创建时间。
回复你第二条：麻烦贴出代码相同的项目地址

ps：我所有的代码都是我一行一行敲的，如果你硬要说我是fork别人的，麻烦拿出确凿的证据

**Comment by Lotus-Blue** [comment]
应该是https://github.com/dengchaojie/flutterDemo这个fork你的
