### ISSUE TITLE
运行起来报错Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.

### ISSUE THREAD

**Issue by lukename** [Mayandev/morec#14]
Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.

**Comment by Mayandev** [comment]
你好，编译问题已经修复，需要更新一些依赖，请重新pull整个项目。
目前在flutter v1.9.1+hotfix.6，iPhoneX 模拟器上成功运行。

**Comment by Mayandev** [comment]
> Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
你好，编译问题已经修复，需要更新一些依赖，请重新pull整个项目。
目前在flutter v1.9.1+hotfix.6，iPhoneX 模拟器上成功运行。
