### ISSUE TITLE
api获取到电影详情页的演员人数。

### ISSUE THREAD

**Issue by jimo17** [Mayandev/morec#16]
您好，请问：我通过https://api.douban.com/v2/movie/subject/:movieid/这个api获取到电影详情页的演员人数为4，但是看您的软件里的电影详情页，不止有4人，请问这是为什么呢？

**Comment by Mayandev** [comment]
> 您好，请问：我通过[https://api.douban.com/v2/movie/subject/:movieid/这个api获取到电影详情页的演员人数为4，但是看您的软件里的电影详情页，不止有4人，请问这是为什么呢？](https://api.douban.com/v2/movie/subject/:movieid/%E8%BF%99%E4%B8%AAapi%E8%8E%B7%E5%8F%96%E5%88%B0%E7%94%B5%E5%BD%B1%E8%AF%A6%E6%83%85%E9%A1%B5%E7%9A%84%E6%BC%94%E5%91%98%E4%BA%BA%E6%95%B0%E4%B8%BA4%EF%BC%8C%E4%BD%86%E6%98%AF%E7%9C%8B%E6%82%A8%E7%9A%84%E8%BD%AF%E4%BB%B6%E9%87%8C%E7%9A%84%E7%94%B5%E5%BD%B1%E8%AF%A6%E6%83%85%E9%A1%B5%EF%BC%8C%E4%B8%8D%E6%AD%A2%E6%9C%894%E4%BA%BA%EF%BC%8C%E8%AF%B7%E9%97%AE%E8%BF%99%E6%98%AF%E4%B8%BA%E4%BB%80%E4%B9%88%E5%91%A2%EF%BC%9F)

加上导演，所以有的不止4个

**Comment by jimo17** [comment]
您好，谢谢您的回复。我还有一个比较蠢的问题（原谅我的蠢）（纯属学术探讨，不是抬杠）。。。
就是：
        同一部电影，豆瓣官方的小程序里面的电影详情里的演员人数超过10，但api里的casts只有4。是因为什么原因呢？需要调用别的api什么的吗？

**Comment by Mayandev** [comment]
> 您好，谢谢您的回复。我还有一个比较蠢的问题（原谅我的蠢）（纯属学术探讨，不是抬杠）。。。
> 就是：
> 同一部电影，豆瓣官方的小程序里面的电影详情里的演员人数超过10，但api里的casts只有4。是因为什么原因呢？需要调用别的api什么的吗？

他们内部使用的应该不是同一个API，本项目是使用豆瓣公开的 API
