### ISSUE TITLE
状态栏显示问题，跳转新页面后返回显示错误

### ISSUE THREAD

**Issue by allstar456** [Mayandev/morec#3]
Mayandev，你好：
发现一个小bug，在我的页面，状态栏显示是白色的，当点击项目地址跳转后，再返回时状态栏显示变黑色的。此时再点击‘我的’按钮，状态栏变白色。我查了下资料，页面的生命周期，在页面重新显示时会调用build方法，通过测试确实调用了build方法，但是‘Screen.updateStatusBarStyle(SystemUiOverlayStyle.light);’这个方法貌似失效了，安卓和ios都存在相同问题。
我是做了一个异步延时操作，视觉上可以解决显示问题，原因不明：
Future.delayed(Duration(microseconds: 200), () {
      Screen.updateStatusBarStyle(SystemUiOverlayStyle.light);
});

**Comment by Mayandev** [comment]
感谢提出的bug，目前已修复。

首先我认为使用延时操作并不妥当，因为当 MyScene 被其他页面覆盖时，都会调用 build 方法，因此如果点击首页，此时还是会调用 MyScene 的 build 方法，这样就会导致首页的 statusbar 显示异常。

另外，需要知道的一点，statusbar 的颜色可以通过 setSystemUIOverlayStyle 改变，同时也取决于当前页面 appbar 的 brightness 属性。而且优先级应该是 brightness > setSystemUIOverlayStyle。你提到的 bug 我认为正是这种原因产生的。

以下是我的解决方法：

首先打印 webview 返回 MyScene 时页面生命周期的顺序如下：

```shell
flutter: my_scene build
flutter: webview deactivate
flutter: webview dispose
```
可以发现，返回时，会先执行上个页面的 build 方法。因此，我将`Screen.updateStatusBarStyle (SystemUiOverlayStyle.light);`这段代码放在了 webview 的 dispose 函数中，问题解决。
