### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ghost** [Mayandev/morec#9]
Launching lib/main.dart on 127.0.0.1:62001 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

Compiler message:
file://.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:199:38: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:////Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      oldImageStream?.removeListener(_handleImageChanged);
                                     ^
file:////Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:200:32: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:////Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      _imageStream.addListener(_handleImageChanged);
                               ^
file:////Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:210:34: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:////Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:////Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    _imageStream?.removeListener(_handleImageChanged);
                                 ^
file:////Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:465:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:////Flutter/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:////Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/palette_generator-0.1.1/lib/palette_generator.dart:188:29: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:////Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:////Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      stream.removeListener(imageListener);
                            ^
file:////Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/palette_generator-0.1.1/lib/palette_generator.dart:194:31: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
        stream.removeListener(imageListener);
                              ^
file:///Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/palette_generator-0.1.1/lib/palette_generator.dart:201:24: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.addListener(imageListener);
                       ^
file:///Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.2.5/lib/photo_view.dart:279:24: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
    stream.addListener(listener);
                       ^
file:///Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.2.5/lib/photo_view.dart:281:29: Error: The argument type 'Null Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///Flutter/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:////flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      stream.removeListener(listener);
                            ^
Compiler failed on /movie/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 648

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugandroid-arm'.
> Process 'command '/Flutter/flutter/bin/flutter'' finishHzed with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Mayandev** [comment]
你是运行了Web模式么？Web模式暂时没有调通

**Comment by black-matt** [comment]
> 你是运行了网络模式么？网络模式暂时没有调通

不是的, 正常运行报错

**Comment by hantianbao** [comment]
你这个问题解决了吗？

**Comment by hantianbao** [comment]
您这个问题解决了吗 ？我现在也遇到了这个问题 ，很头疼  项目一直启动不起来。

**Comment by hanqingkai** [comment]
相同的问题啊，像是flutter的bug，不知道怎么解决啊

**Comment by hantianbao** [comment]
我最后是直接把运行的时候报错的地方注释掉了  至少可以启动项目了 这个问题好像是版本冲突的问题  等有时间把flutter的版本降低试试


------------------ 原始邮件 ------------------
发件人: "hanqingkai"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 上午10:12
收件人: "Mayandev/morec"<morec@noreply.github.com>;
抄送: "NOOB"<986964910@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Mayandev/morec] 运行报错 (#9)




相同的问题啊，像是flutter的bug，不知道怎么解决啊

**Comment by iPatel007** [comment]
In my case, I just updated "cached_network_image: ^0.8.0" in "pubspace.yaml" and work for me.

**Comment by Lotus-Blue** [comment]
你有没有把文件名改成了中文？文件名不能含有英文

**Comment by hantianbao** [comment]
谢谢，是版本的问题




------------------ 原始邮件 ------------------
发件人: "Lotus-Blue"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 晚上9:59
收件人: "Mayandev/morec"<morec@noreply.github.com>;
抄送: "NOOB"<986964910@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Mayandev/morec] 运行报错 (#9)




你有没有把文件名改成了中文？文件名不能含有英文

**Comment by Web3TomCat** [comment]
把报错的库的版本更新到最新就好了。https://pub.dev/packages

**Comment by lukename** [comment]
> 把报错的库的版本更新到最新就好了。https://pub.dev/packages

更新了两个图片的包还是不行

**Comment by lukename** [comment]
Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
